services:
  wblog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./conf:/app/conf
      - ./log:/app/log
      - wblog_data:/app/data
    environment:
      - GIN_MODE=release
    restart: always
    networks:
      - wblog_network

volumes:
  wblog_data:

networks:
  wblog_network: